name: "Node.js CI - Report"

on:
  push:
    paths:
      - ".github/workflows/node.js-report.yml"
      - "report/**"
  pull_request:
    paths:
      - "report/**"

jobs:
  build-report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: report
    - run: npm run build
      working-directory: report
